parse_config:
  # Map raw bindings to human-readable labels
  raw_binding_map:
    "&mo 1": "L1"
    "&mo 2": "Fn2"
    "&kp LALT": "Alt"
    "&kp RALT": "Alt"
    "&kp LCTRL": "Ctrl"
    "&kp RCTRL": "Ctrl"
    "&kp LGUI": "Cmd"
    "&kp RGUI": "Cmd"
    "&kp LSHFT": "Shft"
    "&kp RSHFT": "Shft"
    "&kp LEFT_ALT": "Alt"
    "&kp RIGHT_ALT": "Alt"
    "&kp LEFT_CONTROL": "Ctrl"
    "&kp RIGHT_CONTROL": "Ctrl"
    "&kp LEFT_COMMAND": "Cmd"
    "&kp RIGHT_COMMAND": "Cmd"
    "&kp LEFT_SHIFT": "Shft"
    "&kp RIGHT_SHIFT": "Shft"
    "&kp LA(LC(LG(NUMBER_1)))": "TpLt"
    "&kp LA(LC(LG(W)))": "WApp"
    "&kp LA(LC(LG(S)))": "Spot"
    "&kp LA(LC(LG(C)))": "Chrm"
    "&kp LA(LC(LG(R)))": "Curs"
    "&kp LA(LC(LG(G)))": "GitH"
    "&kp LA(LC(LG(N2)))": "L←"
    "&kp LA(LC(LG(N3)))": "R→"
    "&kp LG(LEFT)": "⌘←"
    "&kp LA(LEFT)": "⌥←"
    "&kp LA(RIGHT)": "⌥→"
    "&kp LG(RIGHT)": "⌘→"
    "&kp LS(LG(N4))": "ScrS"
    "&kp LA(A)": "å"
    "&kp LA(LS(N2))": "€"
    "&kp LA(N3)": "£"
    "&kp UP": "↑"
    "&kp DOWN": "↓"
    "&kp LEFT": "←"
    "&kp RIGHT": "→"
    "&kp ESCAPE": "Esc"
    "&kp ENTER": "↵"
    "&kp BACKSPACE": "⌫"
    "&kp TAB": "Tab"
    "&kp SPACE": "Spce"
    "&kp DELETE": "Del"
    "&kp PLUS": "+"
    "&kp MINUS": "-"
    "&kp EQUAL": "="
    "&kp SLASH": "/"
    "&kp BACKSLASH": "\\"
    "&kp TILDE": "~"
    "&kp GRAVE": "`"
    "&kp SEMI": ";"
    "&kp COLON": ":"
    "&kp SQT": "'"
    "&kp DQT": "\""
    "&kp COMMA": ","
    "&kp DOT": "."
    "&kp FSLH": "/"
    "&kp BSLH": "\\"
    "&kp LEFT_BRACE": "{"
    "&kp RIGHT_BRACE": "}"
    "&kp LEFT_BRACKET": "["
    "&kp RIGHT_BRACKET": "]"
    "&kp LEFT_PARENTHESIS": "("
    "&kp RIGHT_PARENTHESIS": ")"
    "&kp UNDER": "_"
    "&kp KP_MULTIPLY": "×"
    "&bootloader": "Boot"
    "&swedish_a": "å"
    "&swedish_o": "ö"
    "&email": "@"
    "&none": ""
    "&trans": ""
    "&macro_ver": "VER"
    "&stp STP_BAT": "Batt"
    "&bt BT_CLR": "CLR"
    "&bl BL_TOG": "BLTg"
    "&rgb_ug RGB_TOG": "RGB"
    "&bl BL_INC": "BL+"
    "&bl BL_DEC": "BL-"
    "&studio_unlock": "Unlk"

draw_config:
  key_w: 60
  key_h: 56
  split_gap: 30
  combo_w: 28
  combo_h: 22
  font_size: 14
  glyph_tap_size: 14
  glyph_hold_size: 12
  glyph_shifted_size: 10
  # Adjust key layout parameters
  key_rx: 6
  key_ry: 6
  legend:
    mid: {x: 0, y: 0}  # Center the primary legend
    tap: {x: 0, y: 0, font_size: 14}
    hold: {x: 0, y: -12, font_size: 12}
    shifted: {x: 0, y: 12, font_size: 10}
  
  # Background color of the SVG
  svg_fill: "#f5f5f5"
  
  # Customize keymap appearance
  keycaps_style:
    # App shortcuts - orange/warm colors
    L1.WApp: {fill: "#33cc33", stroke: "#1a991a"}
    L1.Spot: {fill: "#1DB954", stroke: "#169042"}
    L1.Chrm: {fill: "#ffaa66", stroke: "#cc8855"}
    L1.Curs: {fill: "#ff9966", stroke: "#cc7755"} 
    L1.GitH: {fill: "#1DB954", stroke: "#169D45"}
    L1.TpLt: {fill: "#ffa64d", stroke: "#cc8840"}
    L1.L←: {fill: "#ffbb77", stroke: "#cc9960"}
    L1.R→: {fill: "#ffbb77", stroke: "#cc9960"}
    
    # Currency symbols - light blue/purple
    L1.€: {fill: "#d1d1ff", stroke: "#9999cc"}
    L1.£: {fill: "#d1d1ff", stroke: "#9999cc"}
    
    # System keys - reddish
    L1.Boot: {fill: "#ff9999", stroke: "#cc7777"}
    Base.L1: {fill: "#ffb3b3", stroke: "#cc8888"}
    Base.Fn2: {fill: "#ffb3b3", stroke: "#cc8888"}
    
    # Special characters - purple
    L1.@: {fill: "#cc99ff", stroke: "#9966cc"}
    L1.ö: {fill: "#cc99ff", stroke: "#9966cc"}
    L1.å: {fill: "#cc99ff", stroke: "#9966cc"}
    
    # Navigation keys - blue
    L1.⌘←: {fill: "#80bfff", stroke: "#6699cc"}
    L1.⌥←: {fill: "#80bfff", stroke: "#6699cc"}
    L1.↑: {fill: "#80bfff", stroke: "#6699cc"}
    L1.⌥→: {fill: "#80bfff", stroke: "#6699cc"}
    L1.⌘→: {fill: "#80bfff", stroke: "#6699cc"}
    L1.←: {fill: "#80bfff", stroke: "#6699cc"}
    L1.↓: {fill: "#80bfff", stroke: "#6699cc"}
    L1.→: {fill: "#80bfff", stroke: "#6699cc"}
    Base.↑: {fill: "#80bfff", stroke: "#6699cc"}
    Base.↓: {fill: "#80bfff", stroke: "#6699cc"}
    Base.←: {fill: "#80bfff", stroke: "#6699cc"}
    Base.→: {fill: "#80bfff", stroke: "#6699cc"}
    
    # Screenshot - bright orange
    Base.ScrS: {fill: "#ffbb77", stroke: "#cc6600"}
    
    # Modifiers - light gray
    Base.Shft: {fill: "#ebebeb", stroke: "#aaaaaa"}
    Base.Ctrl: {fill: "#ebebeb", stroke: "#aaaaaa"}
    Base.Alt: {fill: "#ebebeb", stroke: "#aaaaaa"}
    Base.Cmd: {fill: "#ebebeb", stroke: "#aaaaaa"}
    Base.Spce: {fill: "#ebebeb", stroke: "#aaaaaa"}
    Base.↵: {fill: "#ebebeb", stroke: "#aaaaaa"}
    Base.⌫: {fill: "#ebebeb", stroke: "#aaaaaa"}
    Base.Tab: {fill: "#ebebeb", stroke: "#aaaaaa"}
    Base.Esc: {fill: "#ebebeb", stroke: "#aaaaaa"}
    
  svg_style: |
    /* Base key style */
    .key {
      fill: #ffffff;
      stroke: #aaaaaa;
      stroke-width: 1;
    }
    
    /* Layer title styling */
    .layer-label {
      font-weight: bold;
      font-size: 18px;
      fill: #333333;
      font-family: 'Arial', sans-serif;
    }
    
    /* Text styling */
    text {
      font-family: 'Arial', sans-serif;
      fill: #000000;
      text-anchor: middle;
      dominant-baseline: central;
      font-weight: 700;
      stroke: none;
    } 